"""
Backfill AI overviews from AlphaXiv public API (no key required for reads).
Scans blog_status:pending papers and fetches existing overviews.
"""
import sys
import os
import re
import json
import time
import traceback
import yaml
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock

sys.path.insert(0, os.path.dirname(__file__))

from alphaxiv_client import get_paper_metadata, get_overview
from note_builder import demote_headings

# ─── Config ───
from config import VAULT_PATH, PAPERS_DIR

print_lock = Lock()

def log(msg: str):
    with print_lock:
        print(msg, flush=True)


def scan_pending() -> list:
    """Scan for papers with blog_status: pending."""
    if not os.path.exists(PAPERS_DIR):
        return []

    results = []
    for f in sorted(os.listdir(PAPERS_DIR)):
        if not f.endswith('.md'):
            continue
        fpath = os.path.join(PAPERS_DIR, f)
        with open(fpath, 'r', encoding='utf-8') as fh:
            content = fh.read(8000)

        if not re.search(r'blog_status:\s*"?pending"?', content):
            continue

        fm_match = re.match(r'^---\s*\n(.*?)\n---', content, re.DOTALL)
        if not fm_match:
            continue

        try:
            fm = yaml.safe_load(fm_match.group(1))
        except yaml.YAMLError:
            continue
        if not fm:
            continue

        arxiv_id = fm.get('arxiv_id', '')
        title = fm.get('title', f.replace('.md', ''))

        results.append({
            'filepath': fpath,
            'arxiv_id': arxiv_id,
            'title': title,
        })

    return results


def update_note(filepath: str, overview_text: str, language: str,
                structured_citations: list = None):
    """Update note with AI overview content, remove blog_status: pending."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    if language == 'zh':
        heading = '## AI 综述 (中文)'
        attribution = '> *由 AlphaXiv 生成*'
    else:
        heading = '## AI 综述 (English)'
        attribution = '> *Generated by AlphaXiv*'

    # ── Extract citations from overview text ──
    # Strategy: try heading-based extraction first, then fallback to un-headed block detection
    citations_text = ''

    # Method 1: Explicit citation heading (## 相关引用 / ## Reference / etc.)
    cit_match = re.search(
        r'\n##\s*(?:相关引[用文]|Reference|参考文献?)\s*\n(.*?)\Z',
        overview_text, re.DOTALL)
    if cit_match:
        raw = cit_match.group(1).strip()
        raw = re.sub(r'^\[本节.*?\]\s*\n*', '', raw)
        if len(raw) > 20:
            citations_text = raw
        # Strip the matched citation block from overview
        overview_text = overview_text[:cit_match.start()].strip()

    # Method 2: Un-headed citation block at end of overview
    # Detects paragraph-style citations (numbered/bulleted, with author names + paper titles)
    if not citations_text:
        paras = re.split(r'\n\n+', overview_text)
        cite_start = None
        for i in range(len(paras) - 1, -1, -1):
            p = paras[i].strip()
            if not p: continue
            # Citation indicators (must be specific — avoid matching conclusion paragraphs):
            # 1. Bold paper titles: **Paper Name**
            is_cite = bool(re.search(r'\*\*[^*]{5,}\*\*', p))
            # 2. Numbered list items
            is_cite = is_cite or bool(re.match(r'^\d+[\.\、\)]', p))
            # 3. Venue abbreviations with context
            is_cite = is_cite or bool(re.search(
                r'(?:CVPR|ICCV|ECCV|NeurIPS|ICML|ICLR|AAAI|IJCAI|SIGGRAPH|TPAMI|TOG|WACV|BMVC)[\s\'\'\d]', p))
            is_cite = is_cite or bool(re.search(
                r'(?:arXiv|ACM|IEEE|Proceedings|Conference|Journal)[\s:\.]', p))
            # 4. Academic author+venue+year patterns
            is_cite = is_cite or bool(re.search(
                r'(?:et al\.?|and)\s.*?(?:\(?\d{4}\)?|arXiv|\.\s*In\s|Proceedings\s|Conference\s|Journal\s)', p))
            # 5. Chinese citation description WITH concrete paper reference (not bare "该论文")
            is_cite = is_cite or bool(re.search(
                r'(?:该引用|这篇论文).*?(?:\[.*?\]|arXiv|CVPR|ICCV|NeurIPS|ICML|Proceedings|\d{4})', p))
            if is_cite:
                cite_start = i
            else:
                break

        if cite_start is not None:
            raw_cite = '\n\n'.join(paras[cite_start:]).strip()
            raw_cite = re.sub(r'^\[本节.*?\]\s*\n*', '', raw_cite)
            if len(raw_cite) > 50:
                citations_text = raw_cite
                overview_text = '\n\n'.join(paras[:cite_start]).strip()

    # Method 3: Strip any remaining heading-based references (shouldn't remain after method 1)
    overview_text = re.sub(
        r'\n##\s*(?:相关引[用文]|Reference|参考文献?).*$',
        '', overview_text, flags=re.DOTALL
    ).strip()

    new_section = f'{heading}\n{attribution}\n\n{demote_headings(overview_text)}\n'

    # ── Build citations section ──
    # Method A: Extracted from overview text (headed or un-headed blocks)
    # Method B: Structured citations field from API (fallback)
    if not citations_text and structured_citations:
        cite_lines = []
        for c in structured_citations:
            if isinstance(c, dict):
                title = c.get('title', '') or getattr(c, 'title', '')
                link = c.get('alphaxiv_link', '') or getattr(c, 'alphaxiv_link', '')
                link = link.replace('/paper/', '/abs/') if link else ''
                justification = c.get('justification', '') or getattr(c, 'justification', '')
                if title:
                    cite_lines.append(f'**{title}**')
                    if link: cite_lines.append(f'  - [AlphaXiv]({link})')
                    if justification: cite_lines.append(f'  - {justification}')
                    cite_lines.append('')
        if cite_lines:
            citations_text = '\n'.join(cite_lines).strip()

    if citations_text:
        new_section += f'\n---\n\n## 相关引用\n\n{citations_text}\n'

    # Remove any existing ## 相关引用 section before inserting new one
    # (prevents duplication on re-run when old citations fall outside replacement boundary)
    content = re.sub(
        r'\n---\n\n## 相关引用\n.*?(?=\n## |\Z)',
        '',
        content,
        flags=re.DOTALL,
    )
    content = re.sub(
        r'\n## 相关引用\n.*?(?=\n## |\Z)',
        '',
        content,
        flags=re.DOTALL,
    )

    # Replace placeholder AI section. Use generic boundaries (\n--- or \n##) instead
    # of brittle \n---\n\*Fetched which doesn't exist on all notes.
    if '## AI 综述' in content:
        content = re.sub(
            r'## AI 综述.*?(?=\n---|\n## |\Z)',
            lambda _: new_section.strip(),
            content,
            count=1,
            flags=re.DOTALL,
        )

    # Remove blog_status: pending from frontmatter (handles both quoted and unquoted)
    content = re.sub(r'\nblog_status:\s*"?pending"?\s*\n', '\n', content)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)


def get_overview_with_retry(vid: str, lang: str, max_retries: int = 3) -> dict:
    """Fetch overview with exponential backoff on failure."""
    for attempt in range(max_retries):
        try:
            result = get_overview(vid, lang)
            if result:
                return result
        except Exception as e:
            if attempt < max_retries - 1:
                delay = 2 ** attempt
                log(f'     Retry {attempt + 1}/{max_retries} in {delay}s: {e}')
                time.sleep(delay)
    return None


def process_paper(paper: dict, idx: int, total: int) -> dict:
    """Fetch overview for a single paper and update note."""
    aid = paper['arxiv_id']
    result = {'arxiv_id': aid, 'ok': False, 'language': None}

    try:
        # Get version_id from metadata
        meta = get_paper_metadata(aid)
        vid = meta.version_id if hasattr(meta, 'version_id') else meta.model_dump().get('version_label', '')
        if not vid:
            log(f'  ⚠️ [{idx}/{total}] {aid}: No version_id')
            result['error'] = 'No version_id'
            return result

        # Try Chinese first (with retry), fallback to English
        zh = get_overview_with_retry(vid, 'zh')
        if zh:
            d = zh.model_dump() if hasattr(zh, 'model_dump') else zh
            overview = d.get('overview', '')
            structured_cit = d.get('citations', [])
            if overview and len(overview) > 100:
                update_note(paper['filepath'], overview, 'zh',
                            structured_citations=structured_cit)
                result['ok'] = True
                result['language'] = 'zh'
                log(f'  ✅ [{idx}/{total}] {aid} ZH ({len(overview)}c) {paper["title"][:40]}')
                return result

        # Fallback to English (with retry)
        en = get_overview_with_retry(vid, 'en')
        if en:
            d = en.model_dump() if hasattr(en, 'model_dump') else en
            overview = d.get('overview', '')
            structured_cit = d.get('citations', [])
            if overview and len(overview) > 100:
                update_note(paper['filepath'], overview, 'en',
                            structured_citations=structured_cit)
                result['ok'] = True
                result['language'] = 'en'
                log(f'  ✅ [{idx}/{total}] {aid} EN ({len(overview)}c) {paper["title"][:40]}')
                return result

        log(f'  ⚠️ [{idx}/{total}] {aid}: No overview available')
        result['error'] = 'No overview available'

    except Exception as e:
        msg = str(e)[:100]
        log(f'  ❌ [{idx}/{total}] {aid}: {msg}')
        result['error'] = msg

    return result


def main():
    import argparse
    parser = argparse.ArgumentParser(description='Backfill AI overviews from AlphaXiv public API')
    parser.add_argument('--workers', type=int, default=3, help='Parallel workers (default: 3)')
    parser.add_argument('--dry-run', action='store_true', help='Scan only, no changes')
    args = parser.parse_args()

    papers = scan_pending()
    if not papers:
        log('No papers with blog_status: pending found.')
        return

    log(f'Found {len(papers)} papers with blog_status: pending')

    if args.dry_run:
        for i, p in enumerate(papers, 1):
            log(f'  {i}. [{p["arxiv_id"]}] {p["title"][:60]}')
        return

    log(f'🔧 {args.workers} workers | 📡 Fetching (public API, no key)...')

    results = []
    t0 = time.time()
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {}
        for i, p in enumerate(papers, 1):
            future = executor.submit(process_paper, p, i, len(papers))
            futures[future] = p

        for future in as_completed(futures):
            try:
                r = future.result()
                results.append(r)
            except Exception as e:
                log(f'  ❌ Exception: {e}')

    elapsed = time.time() - t0
    ok = sum(1 for r in results if r['ok'])
    zh_count = sum(1 for r in results if r.get('language') == 'zh')
    en_count = sum(1 for r in results if r.get('language') == 'en')
    fail = len(results) - ok

    log(f'\n{"="*60}')
    log(f'✅ Done in {elapsed:.1f}s')
    log(f'   With overview: {ok} ({zh_count} CN, {en_count} EN)')
    log(f'   Still pending: {fail}')


if __name__ == '__main__':
    main()
