"""
Batch import script - uses arXiv API for metadata (reliable),
falls back to AlphaXiv for AI overviews when available.
"""
import sys
import os
import re
import time
import json
from datetime import datetime

import arxiv

# Try AlphaXiv, but don't fail if unavailable
ALPHAXIV_AVAILABLE = False
try:
    sys.path.insert(0, os.path.dirname(__file__))
    from alphaxiv_client import get_paper_metadata, get_overview, search_paper
    ALPHAXIV_AVAILABLE = True
except Exception:
    pass

from note_builder import (
    clean_title, sanitize_filename, check_title_issues,
    demote_headings, format_citations, CATEGORY_MAP
)
from config import VAULT_PATH

OUTPUT_DIR = os.path.join(VAULT_PATH, '300 Resources', '320 References') if VAULT_PATH else ''


def fetch_arxiv_meta(arxiv_id: str) -> dict:
    """Fetch paper metadata from arXiv API."""
    client = arxiv.Client()
    search = arxiv.Search(id_list=[arxiv_id])
    paper = next(client.results(search))

    authors = [a.name for a in paper.authors]
    categories = list(paper.categories)
    tags = ['paper']
    for cat in categories:
        if cat in CATEGORY_MAP:
            tags.append(CATEGORY_MAP[cat])
    tags = list(dict.fromkeys(tags))

    pub_date = paper.published.strftime('%Y-%m-%d') if paper.published else 'Unknown'

    return {
        'title': paper.title,
        'arxiv_id': arxiv_id,
        'authors': authors,
        'abstract': re.sub(r'\s+', ' ', paper.summary.replace('\n', ' ')).strip(),
        'categories': categories,
        'tags': tags,
        'published': pub_date,
        'arxiv_url': f'https://arxiv.org/abs/{arxiv_id}',
        'alphaxiv_url': f'https://alphaxiv.org/abs/{arxiv_id}',
        'comment': paper.comment or '',
        'journal_ref': paper.journal_ref or '',
        'entry_id': paper.entry_id,
    }


def try_alphaxiv_overview(arxiv_id: str) -> tuple:
    """Try to get AlphaXiv AI overview. Returns (zh_overview, en_overview, warnings)."""
    if not ALPHAXIV_AVAILABLE:
        return None, None, ['AlphaXiv client not available']

    try:
        meta = get_paper_metadata(arxiv_id)
        version_id = meta.version_id
        en = get_overview(version_id, 'en')
        zh = get_overview(version_id, 'zh')

        zh_data = zh.model_dump() if zh else {}
        en_data = en.model_dump() if en else {}

        warnings = []
        if not zh_data.get('overview'):
            warnings.append('Chinese overview empty')
        if not en_data.get('overview'):
            warnings.append('English overview empty')

        return zh_data, en_data, warnings if warnings else []
    except Exception as e:
        return None, None, [f'AlphaXiv fetch failed: {e}']


def build_note_arxiv(meta: dict, zh_overview: dict = None, en_overview: dict = None) -> str:
    """Build Obsidian markdown note from arXiv metadata."""
    title = clean_title(meta['title'])
    arxiv_id = meta['arxiv_id']
    authors = meta['authors']
    tags = meta['tags']
    pub_date = meta['published']
    abstract = meta['abstract']

    now_str = datetime.now().strftime('%Y-%m-%d %H:%M')

    authors_yaml = '\n  - '.join(authors)
    tags_str = ', '.join(tags)

    parts = [f'''---
title: "{title}"
arxiv_id: "{arxiv_id}"
date: {pub_date}
tags: [{tags_str}]
source: "{meta['alphaxiv_url']}"
authors:
  - {authors_yaml}
aliases:
  - {title}
created: {now_str}
---

# {title}

> **arXiv**: [{arxiv_id}]({meta['arxiv_url']}) | **Published**: {pub_date}''']

    if meta.get('journal_ref'):
        parts.append(f'> **Journal**: {meta['journal_ref']}')

    parts.append(f'''
## 摘要

{abstract}

---''')

    # AI overview section
    if zh_overview and zh_overview.get('overview'):
        overview_text = zh_overview['overview']
        overview_text = re.sub(
            r'\n##\s*(?:相关引[用文]|Reference|参考文献?).*$',
            '', overview_text, flags=re.DOTALL
        ).strip()
        parts.append(f'''
## AI 综述 (中文)

> *由 AlphaXiv 生成*

{demote_headings(overview_text)}

---''')
    elif en_overview and en_overview.get('overview'):
        overview_text = en_overview['overview']
        overview_text = re.sub(
            r'\n##\s*(?:相关引[用文]|Reference|参考文献?).*$',
            '', overview_text, flags=re.DOTALL
        ).strip()
        parts.append(f'''
## AI 综述 (English)

> *Generated by AlphaXiv*

{demote_headings(overview_text)}

---''')
    else:
        parts.append('''
## AI 综述

*AI overview not available (AlphaXiv API unreachable). To be updated.*

---''')

    # Citations from AlphaXiv
    if zh_overview and zh_overview.get('citations'):
        parts.append(f'''
## 相关引用

{format_citations(zh_overview['citations'])}

---''')

    parts.append(f'''
*Fetched from arXiv on {now_str}*
''')

    return '\n'.join(parts)


if __name__ == '__main__':
    arxiv_ids = sys.argv[1:] if len(sys.argv) > 1 else []

    if not arxiv_ids:
        print("Usage: python batch_import.py ARXIV_ID [ARXIV_ID ...]")
        sys.exit(1)

    results = []
    for arxiv_id in arxiv_ids:
        print(f'\n{"="*60}')
        print(f'Processing: {arxiv_id}')

        # Step 1: arXiv metadata
        try:
            meta = fetch_arxiv_meta(arxiv_id)
            print(f'  Title: {meta["title"][:80]}')
            print(f'  Authors: {len(meta["authors"])} authors')
            print(f'  Categories: {meta["categories"]}')
        except Exception as e:
            print(f'  ERROR fetching arXiv metadata: {e}')
            continue

        # Step 2: Try AlphaXiv overview
        zh_overview, en_overview, ov_warnings = try_alphaxiv_overview(arxiv_id)
        for w in ov_warnings:
            print(f'  [AlphaXiv] {w}')

        # Step 3: Build note
        content = build_note_arxiv(meta, zh_overview, en_overview)

        # Step 4: Check title issues
        issues = check_title_issues(meta['title'], VAULT_PATH)
        blocks = [i for i in issues if i[0] == 'block']
        if blocks:
            print(f'  BLOCKED: {[b[1] for b in blocks]}')
            continue

        for severity, msg in issues:
            print(f'  [{severity}] {msg}')

        # Step 5: Save
        filename = sanitize_filename(meta['title']) + '.md'
        filepath = os.path.join(OUTPUT_DIR, filename)
        os.makedirs(OUTPUT_DIR, exist_ok=True)

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f'  SAVED: {filepath}')
        results.append({'arxiv_id': arxiv_id, 'filepath': filepath, 'title': meta['title']})

    print(f'\n{"="*60}')
    print(f'Completed: {len(results)}/{len(arxiv_ids)} papers imported')
